name: run-macos-13
on:
  workflow_dispatch:
    inputs:
      commands:
        type: string
        description: zsh commands to run
        required: true
      artifact-directory:
        type: string
        description: directory whose contents will be uploaded as artifacts
        required: false
defaults:
  run:
    shell: /bin/zsh -Negku {0}
jobs:
  run:
    runs-on: macos-13
    env:
      COMMANDS: ${{inputs.commands}}
    steps:
    - name: 🛒 Checkout repo
      env:
        GIT_CONFIG_COUNT: 1
        GIT_CONFIG_KEY_0: init.defaultBranch
        GIT_CONFIG_VALUE_0: ${{github.event.repository.default_branch}}
      uses: actions/checkout@v4
      with:
        # Include all history & tags for Scripts/version
        fetch-depth: 0

    - name: Run commands
      run: eval "${COMMANDS}"

    - name: Upload files as artifact
      if: inputs.artifact-directory != ''
      uses: actions/upload-artifact@v4
      with:
        name: output
        path: ${{inputs.artifact-directory}}*
